### PR TITLE
Build, test, and upload wheels on Github Actions

### PR DESCRIPTION
**Pull request by hoffmang9**
We are going to be using this zstd as a component of chia-blockchain.

I have built this Github Action to create and test wheels for all of the major supported python versions and platforms with the exception of the 32 bit version. The latter can easily be added but the proliferation of linux options is already taking about 90 minutes to complete.

Hopefully the comments are understandable and happy to add/change/answer questions.

The one issue outstanding is that this finds some sort of incompatibility on Windows and Python 3.9.9. The library seems to respond with the version number surrounded in `"` so the version test fails. 

https://github.com/Chia-Network/python-zstd/runs/4645914536?check_suite_focus=true#step:8:679
```
  test_module_version (tests.test_version.TestZstdVersion) ... FAIL
  
  ======================================================================
  FAIL: test_module_version (tests.test_version.TestZstdVersion)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "D:\a\python-zstd\python-zstd\tests\test_version.py", line 8, in test_module_version
      BaseTestZSTD.helper_version(self)
    File "D:\a\python-zstd\python-zstd\tests\base.py", line 49, in helper_version
      self.assertEqual(self.PKG_VERSION, zstd.version())
  AssertionError: '1.5.0.4' != '"1.5.0.4"'
  - 1.5.0.4
  + "1.5.0.4"
  ? +       +
  ```

I will attempt to do a bit more debugging but hope you might have additional thoughts on the root cause of that test failure.

### CODE REVIEW

**Comment by hoffmang9** [comment]
We believe this now compiles correctly under all versions of Python and Windows.

One note from earlier is that, to use the auto publishing to PyPI you will need to add your various PyPI passwords into the Github Secrets for this repo.

**Comment by sergey-dryabzhinsky** [comment]
Thanks. Hope it will not break Linux builds.

**Comment by sergey-dryabzhinsky** [comment]
Or macos builds.
Need someone who can check it.

**Comment by hoffmang9** [comment]
Each wheel is tested by your test harness on each of the various platforms including MacOS x86_64 and both linux platforms. We tested the Apple Silicon version by hand since we all can't yet test on public CIs.

You'll need to [enable GitHub Actions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository) on this repo. Once you do that and ping me - I'll open a PR to test the building in this repo.

**Comment by hoffmang9** [comment]
You can see the tests here for Ubuntu:
https://github.com/Chia-Network/python-zstd/runs/4646531381?check_suite_focus=true#step:8:367

And MacOS:
https://github.com/Chia-Network/python-zstd/runs/4646531350?check_suite_focus=true#step:8:495

**Comment by sergey-dryabzhinsky** [comment]
Good.
Included into 1.5.1.0 release.

**Comment by hoffmang9** [comment]
Are you going to enable Github Actions and set up auto upload to your PyPI account?

It will generate and post these wheels: https://github.com/Chia-Network/python-zstd/suites/4814121287/artifacts/135573095

**Comment by emlowe** [comment]
Bump - can you enable Github Actions for your repo - as this will automatically publish the binary wheels

**Comment by sergey-dryabzhinsky** [comment]
Seems actions do not work well.
Or I do not know how to make it work.

**Comment by sergey-dryabzhinsky** [comment]
It's start working.
But I need some examples to setup it for uploading to pypi or creating attachments to releases.

**Comment by sergey-dryabzhinsky** [comment]
Thanks. Managed it by myself. Seems like working.

**Comment by hoffmang9** [comment]
Thanks very much for getting all of that working to your liking!

As a downstream, it's much appreciated.

**Pull request merged**
